using System;
using System.Collections.Generic;
using System.Text;

namespace DnD_Character_Creator.CharacterPieces.Spells
{
    public static class PsionSpells
    {
        public static List<string> Cantrips { get; set; } = new List<string>
        {
            "Acid Splash",
            "Blade Ward",
            "Chill Touch",
            "Control Flames",
            "Create Bonfire",
            "Dancing Lights",
            "Eldritch Blast",
            "Encode Thoughts",
            "Fire Bolt",
            "Friends",
            "Frostbite",
            "Guidance",
            "Gust",
            "Infestation",
            "Light",
            "Lightning Lure",
            "Mending",
            "Message",
            "Mind Sliver",
            "Minor Illusion",
            "Mold Earth",
            "Poison Spray",
            "Prestidigitation",
            "Primal Savagery",
            "Ray of Frost",
            "Resistance",
            "Sacred Flame",
            "Shape Water",
            "Shocking Grasp",
            "Spare the Dying",
            "Thaumaturgy",
            "Thunderclap",
            "Vicious Mockery",
            "Word of Radiance"
        };
        public static List<string> FirstLvls { get; set; } = new List<string> {
            "Absorb Elements",
            "Animal Friendship",
            "Beast Bond",
            "Burning Hands",
            "Cause Fear",
            "Chaos Bolt",
            "Charm Person",
            "Chromatic Orb",
            "Color Spray",
            "Command",
            "Comprehend Languages",
            "Create or Destroy Water",
            "Cure Wounds",
            "Detect Magic",
            "Disguise Self",
            "Dissonant Whispers",
            "Earth Tremor",
            "Entangle",
            "Expeditious Retreat",
            "False Life",
            "Featherfall",
            "Find Familiar",
            "Gift of Alacrity",
            "Grease",
            "Guiding Bolt",
            "Healing Word",
            "Heroism",
            "Ice Knife",
            "Identify",
            "Inflict Wounds",
            "Jump",
            "Longstrider",
            "Mage Hand",
            "Magic Missile",
            "Shield",
            "Silent Image",
            "Sleep",
            "Speak with Animals",
            "Thunderwave",
            "Witch Bolt"
        };
        public static List<string> SecondLvls { get; set; } = new List<string> {
            "Aganazzar's Scorcher",
            "Alter Self",
            "Augury",
            "Barkskin",
            "Beast Sense",
            "Blindness/Deafness",
            "Blur",
            "Calm Emotions",
            "Crown of Madness",
            "Darkvision",
            "Detect Thoughts",
            "Dragon's Breath",
            "Dust Devil",
            "Enhance Ability",
            "Enlarge/Reduce",
            "Enthrall",
            "Flame Blade",
            "Flaming Sphere",
            "Flock of Familiars",
            "Fortune's Favor",
            "Gentle Repose",
            "Gift of Gab",
            "Gust of Wind",
            "Healing Spirit",
            "Heat Metal",
            "Hold Person",
            "Immovable Object",
            "Invisibility",
            "Lesser Restoration",
            "Levitate",
            "Locate Animals or Plants",
            "Locate Object",
            "Magic Mouth",
            "Melf's Acid Arrow",
            "Mind Spike",
            "Mirror Image",
            "Misty Step",
            "Phantasmal Force",
            "Ray of Enfeeblement",
            "Scorching Ray",
            "See Invisibility",
            "Shadow Blade",
            "Shatter",
            "Spiderclimb",
            "Suggestion",
            "Summon Beast",
            "Tasha's Mind Whip",
            "Warding Bond",
            "Web"
        };
        public static List<string> ThirdLvls { get; set; } = new List<string> {
            "Blink",
            "Catnap",
            "Clairvoyance",
            "Conjure Animals",
            "Conjure Barrage",
            "Counterspell",
            "Create Food and Water",
            "Crusader's Mantle",
            "Daylight",
            "Dispel Magic",
            "Fast Friends",
            "Fear",
            "Feign Death",
            "Fireball",
            "Flame Arrows",
            "Fly",
            "Gaseous Form",
            "Haste",
            "Hypnotic Pattern",
            "Incite Greed",
            "Intellect Fortress",
            "Life Transference",
            "Lightning Arrow",
            "Lightning Bolt",
            "Mass Healing Word",
            "Meld Into Stone",
            "Melf's Minute Meteors",
            "Motivational Speech",
            "Nondetection",
            "Plant Growth",
            "Protection from Energy",
            "Pulse Wave",
            "Sending",
            "Slow",
            "Speak with Dead",
            "Speak with Plants",
            "Spirit Guardians",
            "Summon Fey",
            "Summon Lesser Demon",
            "Summon Shadowspawn",
            "Summon Undead",
            "Thunder step",
            "Tongues",
            "Vampiric Touch",
            "Waterbreathing",
            "Water Walk"
        };
        public static List<string> FourthLvls { get; set; } = new List<string> {
            "Arcane Eye",
            "Banishment",
            "Blight",
            "Charm Monster",
            "Compulsion",
            "Confusion",
            "Conjure Minor Elementals",
            "Conjure Woodland Beings",
            "Death Ward",
            "Dimension Door",
            "Divination",
            "Dominate Beast",
            "Fabricate",
            "Freedom of Movement",
            "Giant Insect",
            "Grasping Vine",
            "Gravity Sinkhole",
            "Greater Invisibility",
            "Guardian of Nature",
            "Leomund's Secret Chest",
            "Locate Creature",
            "Mordenkainen's Faithful Hound",
            "Mordenkainen’s Private Sanctum",
            "Otiluke’s Resilient Sphere",
            "Phantasmal Killer",
            "Polymorph",
            "Shadow of Moil",
            "Stoneskin",
            "Summon Aberration",
            "Summon Construct",
            "Summon Elemental",
            "Summon Greater Demon",
            "Vitriolic Sphere",
            "Watery Sphere"
        };
        public static List<string> FifthLvls { get; set; } = new List<string> {
            "Animate Objects",
            "Antilife Shell",
            "Bigby's Hand",
            "Commune",
            "Commune with Nature",
            "Cone of Cold",
            "Conjure Elemental",
            "Conjure Volley",
            "Contact Other Plane",
            "Creation",
            "Destructive Wave",
            "Dominate Person",
            "Dream",
            "Enervation",
            "Far Step",
            "Geas",
            "Greater Restoration",
            "Hold Monster",
            "Immolation",
            "Infernal Calling",
            "Insect Plague",
            "Legend Lore",
            "Mislead",
            "Modify Memory",
            "Negative Energy Flood",
            "Passwall",
            "Planar Binding",
            "Rary's Telepathic Bond",
            "Reincarnate",
            "Scrying",
            "Seeming",
            "Skill Empowerment",
            "Summon Celestial",
            "Synaptic Static",
            "Telekinesis",
            "Teleportation Circle",
            "Tree Stride",
            "Wrath of Nature"
        };
        public static List<string> SixthLvls { get; set; } = new List<string> {
            "Arcane Gate",
            "Chain Lightning",
            "Conjure Fey",
            "Create Homunculus",
            "Create Undead",
            "Disintegrate",
            "Drawmij's Instant Summons",
            "Eyebite",
            "Find the Path",
            "Flesh to Stone",
            "Forbiddance",
            "Gravity Fissure",
            "Harm",
            "Heal",
            "Invetiture of Flame",
            "Invetiture of Ice",
            "Invetiture of Stone",
            "Invetiture of Wind",
            "Magic Jar",
            "Mass Suggestion",
            "Mental Prison",
            "Otiluke's Freezing Sphere",
            "Otiluke's Irresistible Dance",
            "Planar Ally",
            "Primordial Ward",
            "Scatter",
            "Soul Cage",
            "Summon Fiend",
            "Tasha's Otherworldly Guise",
            "Tenser's Transformation",
            "Transport via Plants",
            "True Seeing",
            "Wind Walk",
            "Word of Recall"
        };
        public static List<string> SeventhLvls { get; set; } = new List<string> {
            "Conjure Celestial",
            "Create Magen",
            "Crown of Stars",
            "Delayed Blast Fireball",
            "Divine Word",
            "Dream of the Blue Veil",
            "Etherealness",
            "Finger of Death",
            "Mordenkainen's Magnificent Mansion",
            "Plane Shift",
            "Power Word Pain",
            "Prismatic Spray",
            "Project Image",
            "Regenerate",
            "Resurrection",
            "Reverse Gravity",
            "Sequester",
            "Simulacrum",
            "Teleport",
            "Tether Essence",
            "Whirlwind"

        };
        public static List<string> EigthLvls { get; set; } = new List<string> {
            "Abi-Dalzim's Horrid Wilting",
            "Animal Shapes",
            "Antipathy/Sympathy",
            "Clone",
            "Darkstar",
            "Demiplane",
            "Dominate Monster",
            "Earthquake",
            "Feeblemind",
            "Glibness",
            "Illusory Dragon",
            "Maddening Darkness",
            "Mind Blank",
            "Power Word Stun",
            "Sunburst",
            "Telepathy"
        };
        public static List<string> NinthLvls { get; set; } = new List<string> {
            "Astral Projection",
            "Foresight",
            "Gate",
            "Invulnerability",
            "Mass Heal",
            "Mass Polymorph",
            "Power Word Heal",
            "Power Word Kill",
            "Psychic Scream",
            "Ravenous Void",
            "Shapechange",
            "Time Stop",
            "True Polymorph",
            "True Resurrection",
            "Weird",
            "Wish"
        };
    }
}
