using System;
using System.Collections.Generic;
using System.Text;

namespace DnD_Character_Creator.CharacterPieces.Spells
{
    public static class SorcererSpells
    {
        public static List<string> Cantrips { get; set; } = new List<string>
        {
            "Acid Splash",
            "Blade Ward",
            "Booming Blade",
            "Chill Touch",
            "Control Flames",
            "Create Bonfire",
            "Dancing Lights",
            "Fire Bolt",
            "Friends",
            "Frostbite",
            "Green-Flame blade",
            "Gust",
            "Infestation",
            "Light",
            "Lightning Lure",
            "Mage Hand",
            "Mending",
            "Message",
            "Mind Sliver",
            "Minor Illusion",
            "Mold Earth",
            "Poison Spray",
            "Prestidigitation",
            "Ray of Frost",
            "Shape Water",
            "Shocking Grasp",
            "Sword Burst",
            "Thunderclap",
            "True Strike"
        };
        public static List<string> FirstLvls { get; set; } = new List<string> {
            "Absorb Elements",
            "Burning Hands",
            "Catapult",
            "Chaos Bolt",
            "Charm Person",
            "Chromatic Orb",
            "Color Spray",
            "Comprehend Languages",
            "Detect Magic",
            "Disguise Self",
            "Distort Value",
            "Earth Tremor",
            "Expeditious Retreat",
            "False Life",
            "Feather Fall",
            "Fog Cloud",
            "Grease",
            "Ice Knife",
            "Jump",
            "Mage Armor",
            "Magic Missile",
            "Ray of Sickness",
            "Shield",
            "Silent Image",
            "Sleep",
            "Tasha's Caustic Brew",
            "Thunderwave",
            "Witch Bolt"
        };
        public static List<string> SecondLvls { get; set; } = new List<string> {
            "Aganazzar's Scorcher",
            "Alter Self",
            "Blindness/Deafness",
            "Blur",
            "Cloud of Daggers",
            "Crown of Madness",
            "Darkness",
            "Darkvision",
            "Detect Thoughts",
            "Dragon's Breath",
            "Dust Devil",
            "Earthbind",
            "Enhance Ability",
            "Enlarge/Reduce",
            "Flame Blade",
            "Flaming Sphere",
            "Gust of Wind",
            "Hold Person",
            "Invisibility",
            "Knock",
            "Levitate",
            "Magic Weapon",
            "Maximilian's Earthen Grasp",
            "Mind Spike",
            "Mirror Image",
            "Misty Step",
            "Phantasmal Force",
            "Pyrotechnics",
            "Scorching Ray",
            "See Invisibility",
            "Shadow Blade",
            "Shatter",
            "Snilloc's Snowball Swarm",
            "Spiderclimb",
            "Suggestion",
            "Tasha's Mind Whip",
            "Warding Wind",
            "Web"
        };
        public static List<string> ThirdLvls { get; set; } = new List<string> {
            "Blink",
            "Catnap",
            "Clairvoyance",
            "Counterspell",
            "Daylight",
            "Dispel Magic",
            "Enemies Abound",
            "Erupting Earth",
            "Fear",
            "Fireball",
            "Flame Arrows",
            "Fly",
            "Gaseous Form",
            "Haste",
            "Hypnotic Pattern",
            "Incite Greed",
            "Intellect Fortress",
            "Lightning Bolt",
            "Major Image",
            "Melf's Minute Meteors",
            "Protection from Energy",
            "Sleet Storm",
            "Slow",
            "Stinking Cloud",
            "Thunder step",
            "Tidal Wave",
            "Tongues",
            "Vampiric Touch",
            "Wall of Water",
            "Waterbreathing",
            "Water Walk"
        };
        public static List<string> FourthLvls { get; set; } = new List<string> {
            "Banishment",
            "Blight",
            "Charm Monster",
            "Confusion",
            "Dimension Door",
            "Dominate Beast",
            "Fire Shield",
            "Greater Invisibility",
            "Ice Storm",
            "Polymorph",
            "Sickening Radiance",
            "Stoneskin",
            "Storm Sphere",
            "Vitriolic Sphere",
            "Wall of Fire",
            "Watery Sphere"
        };
        public static List<string> FifthLvls { get; set; } = new List<string> {
            "Animate Objects",
            "Bigby's Hand",
            "Cloudkill",
            "Cone of Cold",
            "Control Winds",
            "Creation",
            "Dominate Person",
            "Enervation",
            "Far Step",
            "Hold Monster",
            "Immolation",
            "Insect Plague",
            "Seeming",
            "Skill Empowerment",
            "Synaptic Static",
            "Telekinesis",
            "Teleportation Circle",
            "Wall of Light",
            "Wall of Stone"
        };
        public static List<string> SixthLvls { get; set; } = new List<string> {
            "Arcane Gate",
            "Chain Lightning",
            "Circle of Death",
            "Disintegrate",
            "Eyebite",
            "Flesh to Stone",
            "Globe of Invulnerability",
            "Invetiture of Flame",
            "Invetiture of Ice",
            "Invetiture of Stone",
            "Invetiture of Wind",
            "Mass Suggestion",
            "Mental Prison",
            "Move Earth",
            "Otiluke's Freezing Sphere",
            "Scatter",
            "Sunbeam",
            "Tasha's Otherworldly Guise",
            "True Seeing"
        };
        public static List<string> SeventhLvls { get; set; } = new List<string> {
            "Crown of Stars",
            "Delayed Blast Fireball",
            "Dream of the Blue Veil",
            "Etherealness",
            "Finger of Death",
            "Fire Storm",
            "Plane Shift",
            "Power Word Pain",
            "Prismatic Spray",
            "Reverse Gravity",
            "Teleport",
            "Whirlwind"

        };
        public static List<string> EigthLvls { get; set; } = new List<string> {
            "Abi-Dalzim's Horrid Wilting",
            "Demiplane",
            "Dominate Monster",
            "Earthquake",
            "Incendiary Cloud",
            "Power Word Stun",
            "Sunburst"
        };
        public static List<string> NinthLvls { get; set; } = new List<string> {
            "Blade of Diaster",
            "Gate",
            "Mass Polymorph",
            "Meteor Swarm",
            "Power Word Kill",
            "Psychic Scream",
            "Time Stop",
            "Wish"
        };
    }
}
