using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace DnD_Character_Creator.CharacterPieces.Spells
{
    public static class WizardSpells
    {
        public static List<string> Cantrips { get; set; } = new List<string>
        {
            "Acid Splash",
            "Blade Ward",
            "Booming Blade",
            "Chill Touch",
            "Control Flames",
            "Create Bonfire",
            "Dancing Lights",
            "Encode Thoughts",
            "Fire Bolt",
            "Friends",
            "Frostbite",
            "Green-Flame blade",
            "Gust",
            "Infestation",
            "Light",
            "Lightning Lure",
            "Mage Hand",
            "Mending",
            "Message",
            "Mind Sliver",
            "Minor Illusion",
            "Mold Earth",
            "Poison Spray",
            "Prestidigitation",
            "Ray of Frost",
            "Shape Water",
            "Shocking Grasp",
            "Sword Burst",
            "Thunderclap",
            "Toll the Dead",
            "True Strike"
        };
        public static List<string> FirstLvls { get; set; } = new List<string> {
            "Absorb Elements",
            "Alarm",
            "Burning Hands",
            "Catapult",
            "Cause Fear",
            "Charm Person",
            "Chromatic Orb",
            "Color Spray",
            "Comprehend Languages",
            "Detect Magic",
            "Disguise Self",
            "Distort Value",
            "Earth Tremor",
            "Expeditious Retreat",
            "False Life",
            "Feather Fall",
            "Find Familiar",
            "Fog Cloud",
            "Frost Fingers",
            "Grease",
            "Ice Knife",
            "Identify",
            "Illusory Script",
            "Jim's Magic Missile",
            "Jump",
            "Longstrider",
            "Mage Armor",
            "Magic Missile",
            "Protection from Evil and Good",
            "Ray of Sickness",
            "Shield",
            "Silent Image",
            "Sleep",
            "Snare",
            "Tasha’s Hideous Laughter",
            "Tasha's Caustic Brew",
            "Tenser’s Floating Disk",
            "Thunderwave",
            "Unseen Servant",
            "Witch Bolt"
        };
        public static List<string> SecondLvls { get; set; } = new List<string> {
            "Acid Arrow",
            "Aganazzar's Scorcher",
            "Alter Self",
            "Arcane Lock",
            "Arcanist's Magic Aura",
            "Blindness/Deafness",
            "Blur",
            "Cloud of Daggers",
            "Continual Flame",
            "Crown of Madness",
            "Darkness",
            "Darkvision",
            "Detect Thoughts",
            "Dragon's Breath",
            "Dust Devil",
            "Earthbind",
            "Enlarge/Reduce",
            "Flaming Sphere",
            "Flock of Familiars",
            "Gentle Repose",
            "Gift of Gab",
            "Gust of Wind",
            "Hold Person",
            "Invisibility",
            "Jim's Glowing Coin",
            "Knock",
            "Levitate",
            "Locate Object",
            "Magic Mouth",
            "Magic Weapon",
            "Maximilian's Earthen Grasp",
            "Melf’s Acid Arrow",
            "Mind Spike",
            "Mirror Image",
            "Misty Step",
            "Nystul’s Magic Aura",
            "Phantasmal Force",
            "Pyrotechnics",
            "Ray of Enfeeblement",
            "Rope Trick",
            "Scorching Ray",
            "See Invisibility",
            "Shadow Blade",
            "Shatter",
            "Skywrite",
            "Snilloc's Snowball Swarm",
            "Spider Climb",
            "Suggestion",
            "Tasha's Mind Whip",
            "Warding Wind",
            "Web"
        };
        public static List<string> ThirdLvls { get; set; } = new List<string> {
            "Animate Dead",
            "Bestow Curse",
            "Blink",
            "Catnap",
            "Clairvoyance",
            "Counterspell",
            "Dispel Magic",
            "Enemies Abound",
            "Erupting Earth",
            "Fast Friends",
            "Fear",
            "Feign Death",
            "Fireball",
            "Flame Arrows",
            "Fly",
            "Galder's Tower",
            "Gaseous Form",
            "Glyph of Warding",
            "Haste",
            "Hypnotic Pattern",
            "Incite Greed",
            "Intellect Fortress",
            "Leomund’s Tiny Hut",
            "Life Transference",
            "Lightning Bolt",
            "Magic Circle",
            "Major Image",
            "Melf's Minute Meteors",
            "Nondetection",
            "Phantom Steed",
            "Protection from Energy",
            "Remove Curse",
            "Sending",
            "Sleet Storm",
            "Slow",
            "Spirit Shroud",
            "Stinking Cloud",
            "Summon Fey",
            "Summon Lesser Demons",
            "Summon Shadowspawn",
            "Summon Undead",
            "Thunder step",
            "Tidal Wave",
            "Tiny Servant",
            "Tongues",
            "Vampiric Touch",
            "Wall of Sand",
            "Wall of Water",
            "Water Breathing"
        };
        public static List<string> FourthLvls { get; set; } = new List<string> {
            "Arcane Eye",
            "Banishment",
            "Blight",
            "Charm Monster",
            "Confusion",
            "Conjure Minor Elementals",
            "Control Water",
            "Dimension Door",
            "Elemental Bane",
            "Evard's Black Tentacles",
            "Fabricate",
            "Fire Shield",
            "Galder's Speedy Courier",
            "Greater Invisibility",
            "Hallucinatory Terrain",
            "Ice Storm",
            "Leomund’s Secret Chest",
            "Locate Creature",
            "Mordenkainen’s Faithful Hound",
            "Mordenkainen’s Private Sanctum",
            "Otiluke’s Resilient Sphere",
            "Phantasmal Killer",
            "Polymorph",
            "Sickening Radiance",
            "Stone Shape",
            "Stoneskin",
            "Storm Sphere",
            "Summon Aberration",
            "Summon Construct",
            "Summon Elemental",
            "Summon Greater Demon",
            "Vitriolic Sphere",
            "Wall of Fire",
            "Watery Sphere"
        };
        public static List<string> FifthLvls { get; set; } = new List<string> {
            "Animate Objects",
            "Bigby’s Hand",
            "Cloudkill",
            "Cone of Cold",
            "Conjure Elemental",
            "Contact Other Plane",
            "Control Winds",
            "Creation",
            "Danse Macabre",
            "Dawn",
            "Dominate Person",
            "Dream",
            "Enervation",
            "Far Step",
            "Geas",
            "Hold Monster",
            "Immolation",
            "Infernal Calling",
            "Legend Lore",
            "Mislead",
            "Modify Memory",
            "Negative Energy Flood",
            "Passwall",
            "Planar Binding",
            "Rary’s Telepathic Bond",
            "Scrying",
            "Seeming",
            "Skill Empowerment",
            "Steel Wind Strike",
            "Synaptic Static",
            "Telekinesis",
            "Teleportation Circle",
            "Transmute Rock",
            "Wall of Force",
            "Wall of Light",
            "Wall of Stone"
        };
        public static List<string> SixthLvls { get; set; } = new List<string> {
            "Arcane Gate",
            "Chain Lightning",
            "Circle of Death",
            "Contingency",
            "Create Homunculus",
            "Create Undead",
            "Disintegrate",
            "Drawmij’s Instant Summons",
            "Eyebite",
            "Flesh to Stone",
            "Globe of Invulnerability",
            "Guards and Wards",
            "Invetiture of Flame",
            "Invetiture of Ice",
            "Invetiture of Stone",
            "Invetiture of Wind",
            "Magic Jar",
            "Mass Suggestion",
            "Mental Prison",
            "Move Earth",
            "Otiluke’s Freezing Sphere",
            "Otto’s Irresistible Dance",
            "Programmed Illusion",
            "Scatter",
            "Soul Cage",
            "Summon Fiend",
            "Sunbeam",
            "Tasha's Otherworldly Guise",
            "Tenser's Transformation",
            "True Seeing",
            "Wall of Ice"
        };
        public static List<string> SeventhLvls { get; set; } = new List<string> {
            "Create Magen",
            "Crown of Stars",
            "Delayed Blast Fireball",
            "Dream of the Blue Veil",
            "Etherealness",
            "Finger of Death",
            "Forcecage",
            "Mirage Arcane",
            "Mordenkainen's Magnificent Mansion",
            "Mordenkainen’s Sword",
            "Plane Shift",
            "Power Word Pain",
            "Prismatic Spray",
            "Project Image",
            "Reverse Gravity",
            "Sequester",
            "Simulacrum",
            "Symbol",
            "Teleport",
            "Whirlwind"

        };
        public static List<string> EigthLvls { get; set; } = new List<string> {
            "Abi-Dalzim's Horrid Wilting",
            "Antimagic Field",
            "Antipathy/Sympathy",
            "Clone",
            "Control Weather",
            "Demiplane",
            "Dominate Monster",
            "Feeblemind",
            "Illusory Dragon",
            "Incendiary Cloud",
            "Maddening Darkness",
            "Maze",
            "Mighty Fortress",
            "Mind Blank",
            "Power Word Stun",
            "Sunburst",
            "Telepathy",
            "Trap the Soul"
        };
        public static List<string> NinthLvls { get; set; } = new List<string> {
            "Astral Projection",
            "Blade of Diaster",
            "Foresight",
            "Gate",
            "Imprisonment",
            "Invulnerability",
            "Mass Polymorph",
            "Meteor Swarm",
            "Power Word Kill",
            "Prismatic Wall",
            "Psychic Scream",
            "Shapechange",
            "Time Stop",
            "True Polymorph",
            "Weird",
            "Wish"
        };
    }
}
